# Generated by Django 5.2.9 on 2025-12-20 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('kategorieId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('beschreibung', models.CharField(blank=True, max_length=255, null=True)),
                ('benutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Buchung',
            fields=[
                ('buchungId', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('income', 'Einkommen'), ('expense', 'Ausgabe')])),
                ('beschreibung', models.CharField(blank=True, max_length=255, null=True)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum', models.DateField(auto_now_add=True)),
                ('benutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.kategorie')),
            ],
        ),
    ]
