# Generated by Django 5.2.9 on 2025-12-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buchung',
            options={'verbose_name_plural': 'Buchungen'},
        ),
        migrations.AlterModelOptions(
            name='kategorie',
            options={'verbose_name_plural': 'Kategorien'},
        ),
    ]
