# Generated by Django 5.2.9 on 2025-12-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_buchung_options_alter_kategorie_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchung',
            name='datum',
            field=models.DateField(),
        ),
    ]
