# Generated by Django 5.2.9 on 2025-12-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_buchung_datum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchung',
            name='beschreibung',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
