# Generated by Django 5.2.9 on 2025-12-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_buchung_beschreibung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchung',
            name='type',
            field=models.CharField(choices=[('income', 'Einkommen'), ('expense', 'Ausgabe')], max_length=10),
        ),
    ]
