# Generated by Django 5.2.9 on 2025-12-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_buchung_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategorie',
            name='beschreibung',
        ),
    ]
